Class {
	#name : 'MyColorPiece',
	#superclass : 'Object',
	#category : 'Myg-Chess-Core',
	#package : 'Myg-Chess-Core'
}

{ #category : 'rendering' }
MyColorPiece >> renderBishop: aSquare [

	self subclassResponsibility
]

{ #category : 'rendering' }
MyColorPiece >> renderKing: aSquare [

	self subclassResponsibility
]

{ #category : 'rendering' }
MyColorPiece >> renderKnight: aSquare [

	self subclassResponsibility
]

{ #category : 'rendering' }
MyColorPiece >> renderPawn: aSquare [

	self subclassResponsibility
]

{ #category : 'rendering' }
MyColorPiece >> renderQueen: aSquare [

	self subclassResponsibility
]

{ #category : 'rendering' }
MyColorPiece >> renderRook: aSquare [

	self subclassResponsibility
]
